suppress-self-cert-warning: true
database:
#  type: mysql
#  username: root
#  url: "localhost:3306"
  type: sqlite
  location: empire/server/data/empire.db
  defaults:
    # staging key will first look at OS environment variables, then here.
    # If empty, will be prompted (like Empire <3.7).
    staging-key: RANDOM
    username: empireadmin
    password: password123
    obfuscation:
      - language: powershell
        enabled: false
        command: "Token\\All\\1"
        module: "invoke-obfuscation"
    keyword_obfuscation:
      - Invoke-Empire
      - Invoke-Mimikatz
    # TODO VR: Rename or remove
    # an IP white list to ONLY accept clients from
    #   format is "192.168.1.1,192.168.1.10-192.168.1.100,10.0.0.0/8"
    ip-whitelist: ""
    # an IP black list to reject accept clients from
    #   format is "192.168.1.1,192.168.1.10-192.168.1.100,10.0.0.0/8"
    ip-blacklist: ""
modules:
  # TODO VR: I think I deleted this for 5.0
  retain-last-value: false
plugins:
  # Auto-load plugin with defined settings
  csharpserver:
    status: start
directories:
  downloads: empire/server/downloads/
  module_source: empire/server/data/module_source/
  obfuscated_module_source: empire/server/data/obfuscated_module_source/
logging:
  level: INFO
  directory: empire/server/downloads/logs/
  simple_console: true
debug:
  last_task:
    enabled: false
    file: empire/server/data/last_task.txt