name: Remove-KeePassConfigTrigger
authors:
  - '@tifkin_'
  - '@harmj0y'
description: This module removes all triggers from all KeePass configs found by Find-KeePassConfig.
software: ''
techniques:
  - T1033
background: true
output_extension: ''
needs_admin: false
opsec_safe: false
language: powershell
min_language_version: '2'
comments:
  - https://github.com/adaptivethreat/KeeThief
options:
  - name: Agent
    description: Agent to run the module on.
    required: true
    value: ''
script_path: 'empire/server/data/module_source/collection/vaults/KeePassConfig.ps1'
script_end: Get-Process *keepass* | Stop-Process -Force; Find-KeePassconfig | Remove-KeePassConfigTrigger | Format-List | Out-String | %{$_ + "`n"}; 'Remove-KeePassConfigTrigger completed'