name: Lint and Test

on:
  pull_request:
    branches:
      - master
      - sponsors-master
      - dev
      - sponsors-dev
      - 5.0-dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
      - uses: isort/isort-action@master
  test:
    needs: lint
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: Test Python ${{ matrix.python-version }}
    strategy:
      matrix:
        python-version: [ '3.8', '3.9' ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          token: ${{ secrets.RELEASE_TOKEN }}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Bootstrap poetry
        run: |
          curl -sL https://install.python-poetry.org | python - -y
      - id: cache-dependencies
        uses: actions/cache@v1
        with:
          path: /home/runner/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-${{ matrix.python-version }}-poetry-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          poetry install
      - name: Run test suite
        run: |
          poetry run pytest
  test_image:
    needs: test
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: Test Docker Image
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          token: ${{ secrets.RELEASE_TOKEN }}
      - name: Build docker image
        run: docker-compose -f .github/docker-compose.yml build
      - name: Run tests on docker image
        run: docker-compose -f .github/docker-compose.yml run test


