name: Sponsor - Merge public dev branch
on:
  workflow_dispatch:

jobs:
  merge_public_dev:
    if: ${{ github.repository == 'BC-SECURITY/Empire-Sponsors' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          ref: sponsors-dev
          fetch-depth: 0
      - name: Set up upstream repo
        run: |
          git remote add upstream https://github.com/bc-security/empire.git
          git fetch upstream
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Create pr branch
        run: |
          if [ -z "$(git branch --list pre-release/merge-dev)" ]; then
            git checkout -b pre-release/merge-dev
          else
            git checkout pre-release/merge-dev
            git reset --hard origin/sponsors-dev
          fi
      - name: Merge dev branch
        shell: '/bin/bash {0}'
        run: |
          git merge --no-edit upstream/dev
          if [ $? -ne 0 ]; then
            echo "Merge failed. Aborting. This is likely caused by a conflict and the merge must be done manually."
            exit 1
          fi
          
          git diff sponsors-dev --exit-code --quiet
          if [ $? -eq 0 ]; then
            echo "No changes needed to merge."
            echo "MERGE_STATUS=NO_CHANGES" >> $GITHUB_ENV
          else
            echo "Changes needed to merge."
            echo "MERGE_STATUS=CHANGES" >> $GITHUB_ENV
          fi
          exit 0
      - name: Push to GitHub
        if: ${{ env.MERGE_STATUS == 'CHANGES' }}
        run: |
          git push origin pre-release/merge-dev
      - name: Create pull request into sponsors-dev
        if: ${{ env.MERGE_STATUS == 'CHANGES' }}
        uses: thomaseizinger/create-pull-request@1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          head: pre-release/merge-dev
          base: sponsors-dev
          title: public dev into sponsors-dev
          reviewers: ${{ github.event.issue.user.login }}
          body: |
            Hi!
            This PR was automatically generated by the `merge-public` workflow.
            Code commit: ${{ steps.make-commit.outputs.commit }}.
            This PR should be merged with a merge commit, not a squash commit.
            Please make sure that all changes are documented in CHANGELOG.md
