name: Sponsor - Create Release Branch
on:
  workflow_dispatch:
    inputs:
      bumpType:
        description: 'Bump type to use for the release branch.'
        type: choice
        default: patch
        options:
          - patch
          - minor
          - major
        required: true

jobs:
  create_release:
    if: ${{ github.repository == 'BC-SECURITY/Empire-Sponsors' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Setup poetry
        run: |
          curl -sL https://install.python-poetry.org | python - -y
      - name: Change version number
        run: |
          OLD_VERSION=$(poetry version -s)
          poetry version ${{ github.event.inputs.bumpType }}
          APP_VERSION=$(poetry version -s)
          echo "APP_VERSION=$(poetry version -s)" >> $GITHUB_ENV
          sed -i "s/$OLD_VERSION\ BC\ Security/$APP_VERSION\ BC\ Security/" empire/server/common/empire.py
      - name: Create release branch
        run: git checkout -b release/v${{ env.APP_VERSION }}
      - name: Update Changelog
        uses: vinnybod/keep-a-changelog-new-release@1.4.0
        with:
          tag: v${{ env.APP_VERSION }}
          skipDiff: false
      - name: Commit changelog and manifest files
        id: make-commit
        run: |
          git add pyproject.toml CHANGELOG.md empire/server/common/empire.py
          git commit --message "Prepare release ${{ env.APP_VERSION }}"
          echo "::set-output name=commit::$(git rev-parse HEAD)"
      - name: Push new branch
        run: git push origin release/v${{ env.APP_VERSION }}
      - name: Create pull request into sponsors-dev
        uses: thomaseizinger/create-pull-request@1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          head: release/v${{ env.APP_VERSION }}
          base: sponsors-dev
          title: v${{ env.APP_VERSION }} into sponsors-dev
          reviewers: ${{ github.event.issue.user.login }}
          body: |
            Hi!
            This PR was automatically generated by the `start-release` workflow.
            I've updated the version name and code commit: ${{ steps.make-commit.outputs.commit }}.
            This PR should be merged with a merge commit, not a squash commit.
      - name: Create pull request into sponsors-master
        uses: thomaseizinger/create-pull-request@1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          head: release/v${{ env.APP_VERSION }}
          base: sponsors-master
          title: v${{ env.APP_VERSION }} into sponsors-master
          reviewers: ${{ github.event.issue.user.login }}
          body: |
            Hi!
            This PR was automatically generated by the `start-release` workflow.
            I've updated the version name and code commit: ${{ steps.make-commit.outputs.commit }}.
            This PR should be merged with a merge commit, not a squash commit.